### ISSUE TITLE
Missing dep: cytoscape-for-sbgnviz

### ISSUE THREAD

**Issue by jvwong** [PathwayCommons/pathways-search#1]
npm: cytoscape-for-sbgnviz missing in package.json.

**Comment by mj3cheun** [comment]
Oh yes, yesterday, I uploaded a broken version of the site to help Dylan test his code. If you remove the “Temp” commit, which should be the latest one, it should fix things.

Edit: I have reverted that Temp commit, not sure if you use command line for git but if you do "git reset --hard HEAD~1" and then do a pull everything should be good
