### ISSUE TITLE
Pathway Commons app menu 

### ISSUE THREAD

**Issue by jvwong** [PathwayCommons/pathways-search#100]
Add an app menu icon and dropdown to other PC apps.
  - Google analytics menu

![screenshot at jul 19 09-09-18](https://user-images.githubusercontent.com/4706307/28368329-faae4a78-6c61-11e7-998a-6bcfb03dbd49.png)

![screenshot at jul 19 09-04-03](https://user-images.githubusercontent.com/4706307/28368136-4af1e8ce-6c61-11e7-8788-745f10b6d376.png)

  - outlook menu
![outlook_menu](https://user-images.githubusercontent.com/4706307/27985806-b3ff68cc-63c0-11e7-93ab-d5db912d73c7.png)

**Comment by jvwong** [comment]
With respect to 'brand' and navigation, refer to Google Analytics menu bar:

```
<logo> | <property> -<appname>
         <app-specific text>
```

![screenshot at jul 19 09-50-45](https://user-images.githubusercontent.com/4706307/28370295-e650cb7c-6c67-11e7-81e5-22d4de1cd496.png)

**Comment by jvwong** [comment]
Currently we have no other apps and should decide whether the search/view is one app. In this case this issue is premature.

**Comment by jvwong** [comment]
I have a set of app logos in progress. For example search:
![app_icons](https://user-images.githubusercontent.com/4706307/30710897-f3aedb98-9ed4-11e7-9375-bd657ccffa7a.png)

**Comment by IgorRodchenkov** [comment]
Done in the app-ui repo.
