### ISSUE TITLE
Set Random Seed for Layouts 

### ISSUE THREAD

**Issue by cannin** [PathwayCommons/pathways-search#104]
It is disorienting that when I try out the different layout methods, if I go back to one I already tried it isn't the same. Is there a way to set a seed such that users would get consistently get the same layout for a given pathway. Below is a screenshot of the page where this is happening: 

![screen shot 2017-07-12 at 10 39 44 am](https://user-images.githubusercontent.com/790284/28124101-b8244462-66f0-11e7-91c6-1d2ea8a12c9a.png)

**Comment by d2fong** [comment]
@cannin 

These layouts give the same result every time you run them:
* pathway commons preset
* dagre
* klay

Force directed layouts will always have some randomness and variation in the results, but I can reduce it with some settings changes.

Just curious, what has been your favourite layout?

**Comment by IgorRodchenkov** [comment]
Done in the app-ui repo.
