### ISSUE TITLE
Save layout positions per layout option

### ISSUE THREAD

**Issue by d2fong** [PathwayCommons/pathways-search#107]
Use Case:
1.  I run the klay layout and play around with it moving a few nodes, etc.
2.  I then run the dagre layout and then play around with it.  
3.  I switch to the klay layout and it should look exactly as it was before I ran the dagre layout

Potential complications:
1. What if I actually want to run the klay layout again instead of always going back to my modified version?

**Comment by d2fong** [comment]
http://genemania.org/ -- save graph layout states via history

**Comment by d2fong** [comment]
## Todo
### Save graph position history
- i.e refer to the above comments
### Bind collapse/expand event dynamically after each layout
- set cose-bilkent for layoutBy when cose-bilkent is the current layout
- set grid for layoutBy when any other layout is used

**Comment by IgorRodchenkov** [comment]
Done in the app-ui repo.
