### ISSUE TITLE
Layout tweaks

### ISSUE THREAD

**Issue by d2fong** [PathwayCommons/pathways-search#109]
General improvements can be made to the layout results of the sbgn graphs in pathway commons by tweaking each layout's settings.

i.e edge length, direction, etc. can be tweaked to tune the layouts to fit the general characteristics of these graphs.

**Comment by d2fong** [comment]
- [x]  tweak cose-bilkent and then renable it as default
- [x]  tweak klay to make it use less space
- [x]  don't show really long labels (probably just don't show complex node labels)
- [x]  show labels of any node on hover
- [x]  increase size of labels for nodes in general

**Comment by gbader** [comment]
We probably need to figure out better labels for complexes in general.  The genes should be shown somehow, without letting the labels get too long with the state variable information.

**Comment by d2fong** [comment]
@IgorRodchenkov Is there anything that can be done about simplifying/reducing the length of a label like this?

![screen shot 2017-07-13 at 4 04 30 pm](https://user-images.githubusercontent.com/2328291/28185353-ff53160c-67e4-11e7-8359-fc632e414df2.png)

**Comment by IgorRodchenkov** [comment]
I doubt it.. unless data authors/providers start giving short names to complexes and interactions...

**Comment by gbader** [comment]
How does Newt handle these? (I think @jvwong  noted differences earlier in another issue)  Are there biopax fields that could be used differently?

**Comment by IgorRodchenkov** [comment]
I bet NEWT uses the same biopax converter. Dylan, could you please use the same query / sbgn input data in our app and newt?

**Comment by IgorRodchenkov** [comment]
Sorry, I edited my previous email reply (didn't realize it was a github issue thread already...)

**Comment by IgorRodchenkov** [comment]
Anyway, this does not sound like a biopax/sbgn converter  or layout issue to me; it's rather about visualisation, style. I.e., labels should not affect layout; and, labels could be made the same size (proportional to current glyph/node size) regardless the text in them (hide too long text - show like  "blah..." unless the node is selected or mouse overed...)

**Comment by d2fong** [comment]
I am pretty sure Newt truncates text and uses '...' for overflow.  When a user clicks the node, then the full label is displayed in a tooltip. Ugur suggested we do that but I recall Gary and Jeff weren't sold on the idea.

**Comment by d2fong** [comment]
Labels are still really long in Newt:
Load this uri: http%3A%2F%2Fidentifiers.org%2Freactome%2FR-HSA-6804756
![screen shot 2017-07-14 at 12 18 19 pm](https://user-images.githubusercontent.com/2328291/28220734-9989c88e-688e-11e7-9659-2e9682a21abe.png)
Comparison of that really long label in Pathways-Search:
![screen shot 2017-07-14 at 12 24 33 pm](https://user-images.githubusercontent.com/2328291/28220967-6fd04102-688f-11e7-819e-bf621f259edd.png)

**Comment by jvwong** [comment]
I'm getting within-compartment macromolecule labels tripping over each other. Probably a distinct issue (e.g. 'long labels') but stashing here just in case.

e.g. [BMP Signalling Pathway (HumanCyc)](http://www.pathwaycommons.org/pathways/#/view?uri=http%3A%2F%2Fpathwaycommons.org%2Fpc2%2FPathway_3044afd98e7724503d23b3344e315ab8) 

![screenshot at jul 20 15-02-56](https://user-images.githubusercontent.com/4706307/28434273-c957b7ec-6d5c-11e7-8ecf-f4a71f834e85.png)

**Comment by IgorRodchenkov** [comment]
Also, try it on iOS (it worse).

**Comment by d2fong** [comment]
What is worse on iOS?

**Comment by IgorRodchenkov** [comment]
Ah, yesterday, shortly after the app update, I noticed that on iPhone it did not look like in my desktop Chrome page: labels were way too large and bold, and - no mouse-over of course... Well, now as I tried again it looks prettier, and probably just as expected; so ignore my comments, sorry ;)
