### ISSUE TITLE
More accurate graph size in the listing

### ISSUE THREAD

**Issue by d2fong** [PathwayCommons/pathways-search#111]
`num interactions` is taken from the pathway commons response, but that is not necessarily how large the graph will be once nodes are filtered. 
A better estimate would be to take cy.nodes().size().

Requires - refactor cy to be passed as a prop instead of being localized state of the viewer

**Comment by jvwong** [comment]
Can you provide a little more info on what this issue is addressing? Where is ```num interactions``` appearing and how does it affect the graph?

**Comment by IgorRodchenkov** [comment]
Done in the app-ui repo.
