### ISSUE TITLE
Google indexing

### ISSUE THREAD

**Issue by jvwong** [PathwayCommons/pathways-search#119]
https://stackoverflow.com/questions/8925397/how-to-let-google-index-my-database-driven-pages-that-are-not-direcly-linked-t
https://support.google.com/webmasters/answer/156184?hl=en

**Comment by cannin** [comment]
Remember that the indexing will show/use text. I'm not sure how much text there is on any of the pages.

**Comment by cannin** [comment]
Add description text around (above, below or side) the pathway. Examples: 

http://www.pathwaycommons.org/pc/record2.do?id=486063
https://www.mycancergenome.org/content/molecular-medicine/pathways/TGF-beta-signaling

The current setup with the linked modal text is 1) completely not obvious what happens when the link is clicked, and 2) the text is rendered after clicking on the link. I don't see a reason why a Google robot would display that text as a search result even though it should be in the search result.

**Comment by hmtinc** [comment]
Here's a sitemap that includes all 5899 pathways which I generated from the pc2 v9 data dump (http://www.pathwaycommons.org/archives/PC2/v9/).  

After App-UI is completed with dynamically generated titles and descriptions, You should be able to pass google the full site map to get it to index the entire site. 


* [sitemaps.zip](https://github.com/PathwayCommons/pathways-search/files/1359662/sitemaps.zip)

* [SBGN -> Sitemap Script](https://github.com/PathwayCommons/pathways-search/files/1359683/sitemapCreator.zip)

**Comment by jvwong** [comment]
waiting for 

- header info in pathway

**Comment by gbader** [comment]
will these lead to a human readable pathway landing page?

**Comment by jvwong** [comment]
As mentioned above by @cannin, pathway-associated 'comments' that end up in the link are [hit](http://www.pathwaycommons.org/pathways/#/view?uri=http%3A%2F%2Fpathwaycommons.org%2Fpc2%2FPathway_3044afd98e7724503d23b3344e315ab8) and [miss](http://www.pathwaycommons.org/pathways/#/view?uri=http%3A%2F%2Fpathwaycommons.org%2Fpc2%2FPathway_5833931c7ae4898ab757c1714947fb71) . 

The rationale for downplaying the text and placing it in a modal link was 1) Many/majority cases have no useful text comments 2) Text creeps in on pathway view real estate. 

I'm not clear on how indexing works but would listing the gene/entity names on each page help say when comments are not? Also related, I noticed SMPDB generates very good hits for images of their [pathway drawings](https://www.google.ca/search?q=smpdb+mu-opioid&client=ubuntu&hs=T69&channel=fs&dcr=0&source=lnms&tbm=isch&sa=X&ved=0ahUKEwiz_4j8hNzWAhUa24MKHZYrDHcQ_AUICygC&biw=1244&bih=1273). Could PNG snapshots of pathways be associated?

**Comment by IgorRodchenkov** [comment]
To do in the app-ui repo.
