### ISSUE TITLE
Remove footer

### ISSUE THREAD

**Issue by jvwong** [PathwayCommons/pathways-search#12]
Can we hide the footer for now? Maybe causing an issue on mobile, for example, Android::Chrome the footer is not fixed but rather can be dragged  upward toward the lower-middle part of the screen.  

![capture _2017-01-17-22-12-13](https://cloud.githubusercontent.com/assets/4706307/22049693/0da000b6-dd03-11e6-8986-0866cfd9b97e.png)

**Comment by mj3cheun** [comment]
The above mess is caused by the length of the sample text that was put into place. I have shortened it in the following commit which fixes the issue: 36ab19103accecdb06a77b2b6a3e7151be9b60c2. If this is acceptable we can close it off here, or if you prefer we can still remove the footer.
