### ISSUE TITLE
Erroneous edges

### ISSUE THREAD

**Issue by jvwong** [PathwayCommons/pathways-search#127]
Production arrows (filled) are pointing towards process nodes rather than away.

 Breaking case: [Transcriptional activation of cell cycle inhibitor p21 (Reactome)](http://www.pathwaycommons.org/pathways/#/view?uri=http%3A%2F%2Fidentifiers.org%2Freactome%2FR-HSA-69895)

![bug_graph_transcriptionalactivationofcellcycleinhibitorp21reactome_browser](https://user-images.githubusercontent.com/4706307/29521192-7204f1c6-8652-11e7-956a-4840d96d1793.png)

**Comment by d2fong** [comment]
Pretty sure this has been fixed in cytoscape.js unstable, reopen if you still see it.
