### ISSUE TITLE
Add node search capability

### ISSUE THREAD

**Issue by cannin** [PathwayCommons/pathways-search#130]
This is a TP53 pathway (title). 

http://www.pathwaycommons.org/pathways/#/view?uri=http%3A%2F%2Fidentifiers.org%2Freactome%2FR-HSA-6803211

It isn't intuitive where TP53 is. Found it by uncollapsing the nodes.

**Comment by hmtinc** [comment]
@jvwong Should the search feature automatically expand parent nodes based on the search parameter?

**Comment by d2fong** [comment]
https://github.com/d2fong/cytoscape.js-compound-collapse/blob/master/src/collection/collapse.js#L40

**Comment by IgorRodchenkov** [comment]
Done in the app-ui repo.
