### ISSUE TITLE
At least one graph shows a blank image when downloaded

### ISSUE THREAD

**Issue by d2fong** [PathwayCommons/pathways-search#134]
related to branch ```cleanup```

URI: http%3A%2F%2Fidentifiers.org%2Freactome%2FR-HSA-1855167

Doesn't happen in the production version of the app, so it is either a bug specifically for cy.mount() or a bug introduced in unstable since cy.js 3.2

**Comment by d2fong** [comment]
Have only been able to find this behaviour when viewing the specified uri

**Comment by IgorRodchenkov** [comment]
Done in the app-ui repo.
