### ISSUE TITLE
Download image

### ISSUE THREAD

**Issue by jvwong** [PathwayCommons/pathways-search#14]
View pane should provide capability to download bitmap image of pathway.

**Comment by mj3cheun** [comment]
Fixed in commit 0c3187045c2f73ca0c7697bda5ade7ac03612f9b. Added download image button.

**Comment by ugurdogrusoz** [comment]
Looks like resolution is really low; should be increased.

**Comment by mj3cheun** [comment]
At the moment, the image download button acts pretty much like a screenshot button, the resolution of the image is the exact same as the resolution of sbgnviewer. Currently investigating ways of improving resolution. Will likely try to use the scale option from cytoscape.

**Comment by mj3cheun** [comment]
Fixed in commit 1a0f6b8be8049022fd2566baf0be2077863ddb95. Increased resolution of output image by 10.
