### ISSUE TITLE
Layout - Frontend

### ISSUE THREAD

**Issue by jonahdlin** [PathwayCommons/pathways-search#142]
# Frontend

- Login modal
	- Option for admin to log in and get additional privileges for layouts
- Admin modal
	- Gives the admin options to override all layouts with the current layout
- Submit layout button
	- Gets information about current layout and sends it to backend for posting
- Possible integration with Harsh's sidebar

**Comment by jvwong** [comment]
let's keep life simple and assume no related changes to the View UI.
