### ISSUE TITLE
Layout - Backend (Post)

### ISSUE THREAD

**Issue by jonahdlin** [PathwayCommons/pathways-search#143]
# Backend (Post)

Sends information about new layouts to the database (and the heuristics algorithm).

- Information it needs from the frontend
	- URI
	- Layout
	- Username
- Information it needs from the database
	- Has to get the URI ID from the database for the URI of the submitted layout, if it doesn't exist then create it
- Needs to check in some way if things have changed
	- If the URI has changed
	- If the graph itself has changed, nodes or edges added, removed, or changed
- Login
	- Validate login information
		- Password security?
		- Should put a warning in the frontend about password security

**Comment by jvwong** [comment]
- frontend: only URI should be necessary. Algorithmic layouts can be done in the client as some are  'non-deterministic'. Punt any authorization/authentication.
- database: should not concerned with URI alterations. For changes to contents, this woulnd't be the database but the 'data' pipeline, which is likely a whole separate set of issues.  
- login: for MVP let's punt logins etc. Who wants to manage that?

**Comment by IgorRodchenkov** [comment]
Done in the app-ui repo.
