### ISSUE TITLE
Layout - Registration

### ISSUE THREAD

**Issue by jonahdlin** [PathwayCommons/pathways-search#144]
# Registration

This is the absolute lowest priority, but would be important if permissions are ever given to non-lab members. This would be a service where a PIN or code is given to users that should be given higher priority for layouts (e.g. a student who wants to help with layouts). This is a rabbit hole of features.

**Comment by jvwong** [comment]
These issues seem generic trade-offs to crowd-sourcing. Consider some alternatives to having an authentication/authorization layer...

Alternative 1:  'Read-only' and 'Edit' links given out on as-needed basis
Alternative 2:  Periodically save-out layouts; Provide a list of updated pathway views to review
Alternative 3: Heuristics for detection of nefarious / erroneous / bad activity
Alternative 4: No restrictions whatsoever
