### ISSUE TITLE
Retrieving Additional Metadata for Pathways

### ISSUE THREAD

**Issue by hmtinc** [PathwayCommons/pathways-search#146]
# Metadata Reterival 

Since the ultimate goal is to allow for users to view metadata when a node is selected or hovered upon, a method will need to be derived to pull this data from the pc2 web service while ensuring the data is properly paired with the nodes. 

- Additional modifications may have to be made to the the backend for pathway commons to enable more data to be included in the initial file set to the client.

- Data retrieved will have to be stored In the data object of the cytoscape elements, which should allow easy access when an element based event is triggered.

**Comment by jvwong** [comment]
Good place to list the minimal meta-data that we would want to carry over to the app.

- [ ] Comments
- [ ] External database identifier, link to

etc.

**Comment by hmtinc** [comment]
- [ ] Comments
- [ ] External database identifier, link to
- [ ] Name
- [ ] ID
- [ ] Datasource
- [ ] Reference
  
These are some values we could carry over, but the BioPax files contain a lot more information then what we'll end up displaying. For future use, should the the values we won't be displaying in the tooltip be stored in the cytoscape object?

**Comment by hmtinc** [comment]
@jvwong  I've managed to develop a rough mapping of biopax data to Cytoscape nodes, but I am still slightly confused on what information should be displayed. There seems to be multiple name fields and multiple comment fields. 

![screen shot 2017-10-12 at 1 39 26 pm](https://user-images.githubusercontent.com/1313810/31511373-88e43f88-af55-11e7-9d1e-212ea8c0d606.png)

**Comment by jvwong** [comment]
This is a major headache in biology - many names,  one gene. 
Perhaps show 'standardName', 'displayName' and maybe comma-separate the list of 'name' values?

**Comment by hmtinc** [comment]
Going through the pathways.txt file on PC2, some of the pathways just seem to fail when a request is sent. 

![screen shot 2017-10-13 at 2 53 52 pm](https://user-images.githubusercontent.com/1313810/31561597-66f9aff8-b026-11e7-8f3b-d9a9f8db5b1e.png)

So far the following have failed

  ✖ http://pathwaycommons.org/pc2/Pathway_d722fda7caea327a65554509149a6e16
  ✖ http://identifiers.org/reactome/R-HSA-5663213
  ✖ http://identifiers.org/reactome/R-HSA-5663205
  ✖ http://identifiers.org/reactome/R-HSA-5663202
  ✖ http://identifiers.org/reactome/R-HSA-5663084
  ✖ http://pathwaycommons.org/pc2/Pathway_86dfeefab680cec9bb206120fde3f123
  ✖ http://pathwaycommons.org/pc2/Pathway_b40d10ab681591416c868eb1dca97916
  ✖ http://pathwaycommons.org/pc2/Pathway_457921d3b8bda28d1b03c267b0a33fdf
  ✖ http://pathwaycommons.org/pc2/Pathway_95ebe83ca96eb263fa6b67099bee7eb0
  ✖ http://pathwaycommons.org/pc2/Pathway_38117f69b79b405c20992e4a562500d9
  ✖ http://pathwaycommons.org/pc2/Pathway_2bffe38600ede77fa1e182e0977f4fba
  ✖ http://pathwaycommons.org/pc2/Pathway_be348f6ec9bd7fd02931cc28ab777c8b
  ✖ http://identifiers.org/reactome/R-HSA-6809583
  ✖ http://pathwaycommons.org/pc2/Pathway_4e70c2e9b0e9568d4a494e69777380c9
  ✖ http://identifiers.org/reactome/R-HSA-6807004
  ✖ http://identifiers.org/reactome/R-HSA-6807047
  ✖ http://identifiers.org/reactome/R-HSA-6807070
  ✖ http://pathwaycommons.org/pc2/Pathway_8b71f6c0cde075db5b92c3d0bbcf3438
  ✖ http://pathwaycommons.org/pc2/Pathway_ccdf95bbb8827aad8a8f37ff24ca35b6
  ✖ http://pathwaycommons.org/pc2/Pathway_1b78757eb02c31af18fd1206f5ca62b5

Are these URI's still valid?

**Comment by jvwong** [comment]
I checked the first three and they worked for me (e.g. http://www.pathwaycommons.org/pathways/#/view?uri=http://identifiers.org/reactome/R-HSA-5663213)

What is you definition of fail? Some pathways are indeed 'blackbox' / empty

**Comment by hmtinc** [comment]
Interesting. I've been encoding the URI component since some of the pathway uri's have special characters, and it doesn't seem to work when encoded.

I figured if no SBGN/Biopax file is returned, then the uri would be considered invalid, as the graph can't be produced without those files.

**Comment by jvwong** [comment]
Can you clarify if these work for you? I checked some and they are indeed valid BioPAX and SBGN but just 'blackbox' pathways.

**Comment by hmtinc** [comment]
They work now. The mapping script wasn't properly parsing the returned result which caused it to throw an error. 

Blackbox pathways or empty pathways  work and are parsed normally.
