### ISSUE TITLE
Add Metadata Tooltip 

### ISSUE THREAD

**Issue by hmtinc** [PathwayCommons/pathways-search#147]
# Metadata Tooltip 

Data received from pc2 service needs to be bound to each and every node and associated with a tooltip that displays a brief view of the metadata.  What should appear in the tooltip, is yet to be determined, but it should also provide an option to expand the information out into either a popup modal or a sidebar.

**Comment by jvwong** [comment]
what's the difference between this and #145 ?

**Comment by hmtinc** [comment]
#145 is an issue/ticket that addresses actually integrating the extension into the view project. 

This issue/ticket refers to actually designing the appearance of the tooltip and linking the metadata to the tooltip.

**Comment by jvwong** [comment]
OK understood. I had success with putting in mockups in issues and getting comments.

**Comment by hmtinc** [comment]
Mockup of tooltip

* When the user selects or hovers over a node, a pop-up will appear that will load in Metadata from a map of SBGN nodes -> BioPax data 

![loading](https://user-images.githubusercontent.com/1313810/30927442-7f572f96-a386-11e7-9044-23b00ad080ee.png)

* When data is loaded in a tab based view will be offered, which will default to the primary information screen. Additionally, a dock button will be offered that, will provide the ability to dock tooltips to the side of the screen for a larger view. 

![popup](https://user-images.githubusercontent.com/1313810/30927498-a98b103e-a386-11e7-9e6f-49d4481aa761.png)

* When tooltips are docked to the side of the screen they’ll appear in a scrollable side bar which will allow multiple tooltips to be docked at a time. The scrollable side bar will shift the header to the right to avoid overlap. Additionally, the sidebar will disappear when no tooltips are docked. 

![multiple](https://user-images.githubusercontent.com/1313810/30927545-c5290026-a386-11e7-8386-4c935ac84076.png)

**Comment by jvwong** [comment]
1. What is the rationale for the docking capability? 
  - For example, would a user demand: "I want see information for both genes of an interaction"?

2. What actual information will you display and how will it be laid out?
  - Don't underestimate this part - how are we helping the user? Data dumping will be not be useful and possibly frustrating. What are the most useful metadata? How/Are the data fields related? What about missing data? Will metadata for different glyphs be different?

**Comment by hmtinc** [comment]
* Rationale was that if a user wanted to view information for multiple at a time they could dock the tooltips. It also could be used to display a more permanent version of the tooltip, as with tippy the tooltip only is display while the mouse is hovering above the node. 

*  I was going to mainly just show some basic values such as name, database identifiers, evidence, curators, and comments. Metadata for different elements will most likely be different as not all elements represent the same types of data, still working on how that would be handled within the tooltip.

**Comment by hmtinc** [comment]
So, to avoid tabs I think it would be best to cut down on the metadata and follow what some desktop based viewers already show 

* Name 
* ID 
* Datasource 
* Reference 
* Comments (Ideally will be cut down to just be the first few relevant sentences which often include the reviewer name)

This should allow all the data to reasonably fit in one slightly larger tooltip, which will most likely dynamically resize to avoid having scroll bars. Additional the tooltip will most likely have a fixed max size which will be based on the view height, to avoid the resized tooltip form going off screen.

![large](https://user-images.githubusercontent.com/1313810/30970728-e0c55426-a433-11e7-8c22-0fc93db61c17.png)

The Metadata tooltips will also provide a document button to obtain a file containing the full dataset for that specific node. This should provide the opportunity  for less relevant data to still be available to the user. This data button could ideally also be linked to some form of pop-up that displays the raw data for users who really wish to view the full set of data.

Lastly, the metadata tooltips would ideally have a dock button to enable the user to temporarily attach the tooltip to the bottom of the view, thus allowing the user to see information for multiple genes of an interaction. Additionally, it will enable the user to view the tooltip without hovering above the node itself.

![dock](https://user-images.githubusercontent.com/1313810/30971066-edb30b6e-a434-11e7-958a-bb8a253f7323.png)

**Comment by jvwong** [comment]
I agree with your metadata fields and order. 

For large amounts of information, an alternative to a document in 'See more info' link with scrolling, like we did with the search. I suspect most people won't go beyond the first couple of fields.

I dunno about the docking. I wonder what users would say...

**Comment by hmtinc** [comment]
Alot of _Styling_ and _Ordering_  still has to be done, but this is how the tooltip currently looks. 
![screen shot 2017-10-31 at 9 46 00 am](https://user-images.githubusercontent.com/1313810/32227460-e1696eaa-be21-11e7-8dda-e3e01c1e6c34.png)
