### ISSUE TITLE
Switching layouts before previous animation finishes stops layout switch

### ISSUE THREAD

**Issue by jonahdlin** [PathwayCommons/pathways-search#153]
![layoutbug](https://user-images.githubusercontent.com/15696989/31246625-f29808d0-a9db-11e7-8c0d-4fa1f5b0f270.gif)

If a layout with an animation is clicked ("layout 1"), and then during the moving animation a different layout is clicked ("layout 2"), the layout reverts to "layout 1", but still displays "layout 2" in the dropdown menu as though it was currently applied. The bug is most reproducible with the Force Directed (cola) layout, since its animation takes the longest to complete.

**Comment by IgorRodchenkov** [comment]
To do in the app-ui repo or ignore it.
