### ISSUE TITLE
Generic Search

### ISSUE THREAD

**Issue by jvwong** [PathwayCommons/pathways-search#154]
Support search for other types.

### Use case
A user is interested in finding more information about the opioid pathway and lands on a result from [Reactome: Opioid Signalling](http://www.pathwaycommons.org/pathways/#/view?uri=http%3A%2F%2Fidentifiers.org%2Freactome%2FR-HSA-111885).  The user may desire more  information about say, the [mu-type opioid receptor](http://www.uniprot.org/uniprot/P35372) named 'OPRM1'. 

This could include:  

a. Drug interactions e.g. [
Propoxyphene napsylate acts as an agonist | DrugBank](http://www.pathwaycommons.org/pathways/#/view?uri=http://pathwaycommons.org/pc2/Control_c61af8349c98ace4e81f57aeb774d27d)
b. Protein interactions e.g. [
GASP-1 interacts with MOR | BIND](http://www.pathwaycommons.org/pathways/#/view?uri=http://pathwaycommons.org/pc2/MolecularInteraction_c289de60-0bbb-4f27-98ee-91ff171600fa___null__1371677_)
c. Regulation via microRNAs e.g. [
hsa-miR-3927-5p regulates OPRM1 | miRTarBase](http://www.pathwaycommons.org/pathways/#/view?uri=http://identifiers.org/mirtarbase/MIRT618118)
d. Phosphorylation e.g. [CAMK2A | PhosphositePlus](http://www.pathwaycommons.org/pathways/#/view?uri=http://pathwaycommons.org/pc2/Catalysis_c29c47140f9c22447102d868ea8c1c6d)

Caveat is that an unrestricted PC search of [OPRM1](http://www.pathwaycommons.org/pc2/search.xml?q=OPRM1) will not necessarily return / rank these well. 

![integration_pc_muopioid](https://user-images.githubusercontent.com/4706307/31317520-5beed440-ac10-11e7-9c88-64478a2298f5.png)

**Comment by jvwong** [comment]
Types to include in search:

1. Pathway
2. Catalysis
3. Interaction / MolecularInteraction
4. TemplateReactionRegulation

tabbed for each class?

**Comment by jvwong** [comment]
Pro-tip: One can comma-separate URIs in webservices GET and Viewer uri parameter.

![screenshot at oct 12 15-56-55](https://user-images.githubusercontent.com/4706307/31516268-ffc9f8bc-af65-11e7-8ac8-2862676d3d5f.png)

**Comment by jvwong** [comment]
Realized that 'type=interaction' is too generic (see BioPAX class hierarchy below). Also we should use more meaningful text labels.

Consider restricting the search-tabs types. Also need text labels that are more meaningful to users, but this is tricky:

1. type=Pathway (label = 'Pathway')
2. type=Catalysis (label = 'Catalysis')
3. type=MolecularInteraction (label = 'Molecular Interaction')
4. type= TemplateReactionRegulation (label = 'Transcription/Translation')
 
![screenshot at oct 13 11-21-55](https://user-images.githubusercontent.com/4706307/31554066-663f2550-b00a-11e7-8e5b-7f33832772c3.png)

**Comment by d2fong** [comment]
Ok thats fine.

I found a query that has null names.
q=oprm1&type=Catalysis

In that case, what should I display for the title?

**Comment by d2fong** [comment]
Can you elaborate on what you do to get drugbank results?

**Comment by jvwong** [comment]
These are toughies...

### No names

Sure this is common, e.g. [GRK2 phosphorylation of OPRM1 (PSP)](http://www.pathwaycommons.org/pathways/#/view?uri=http://pathwaycommons.org/pc2/Catalysis_8152e4a044fca56d202953c0e915ad1e).

I previously hacked the Viewer to show the URI when no name existed which is not acceptable. Both 'Search' and 'Viewer' components will have to handle SearchHits and URI/objects, respectively,  in a generic fashion with sane defaults. 

The user needs some useful hints about that object's contents to identify those of interest within a list. In the absence of a human-readable name,  a close second could be a list of participants/genes. I wonder how expensive and complicated using traverse is e.g. for GRK2 phosphorylation of OPRM1 (PSP) we can grab the 
 [controller genes](http://www.pathwaycommons.org/pc2/traverse?uri=http://pathwaycommons.org/pc2/Catalysis_8152e4a044fca56d202953c0e915ad1e&path=Catalysis/controller:PhysicalEntity/displayName) and [controlled genes](http://www.pathwaycommons.org/pc2/traverse?uri=http://pathwaycommons.org/pc2/Catalysis_8152e4a044fca56d202953c0e915ad1e&path=Catalysis/controlled:Interaction/participant*/displayName)

----------  

### Drug bank

I used [this query](http://www.pathwaycommons.org/pc2/search.json?q=P35372&datasource=drugbank) - of course, the resulting 'type=Control' results are of interest but would not be included in our four types above. 

Maybe we use 'type=control' (label = 'Reactions') instead of the two specific classes catalysis and templateReactionRegulation?

**Comment by d2fong** [comment]
@IgorRodchenkov 

Hey Igor, Jeff and I noticed that sometimes searchresult.searchit entries have a null name.  Do you have any tips to generate a name for these search results in the way Jeff described above?

**Comment by IgorRodchenkov** [comment]
I think, it's quite common that biopax interaction type objects have no names at all...
Yes, we could simply use the biopax type as name or auto-generate a display name using type and participant names (or even states - features, locations), but these would result in too long names (e.g., if there are many participants and we would use left/right/controller/product/etc. property names, and cellular location...). Let's brainstorm and implement 'name auto-fill' in the next release PC10?

**Comment by IgorRodchenkov** [comment]
@d2fong , @jvwong 
Reading your comments I thought that it worth clarifying something...
PC search query engine does take into account BioPAX ontology - class hierarchy.
So, if you filter by type, e.g., by adding `'&type=Control'`, you get Control and its sub-class interactions (Catalysis, etc.); `'type=Entity'` - gets you interactions, pathways, physical entities and genes; `''type=Conversion''` - finds only reactions, etc.

**Comment by IgorRodchenkov** [comment]
Oops, @d2fong @jvwong , I mean - 
 `''type=Conversion''` - finds reactions only (incl. transport).

**Comment by jvwong** [comment]
Good idea to get a PC10 'name/details' auto-fill field - it could simply be type and say, the first five participant display names: `<type>: <gene ID 1>...<gene ID 5>`

--------

Lemme recap the potential search tab/types:

1. Pathway (label='Pathways')
2. MolecularInteraction (label='Molecular Interaction')
3. Control  (label='Reactions')
4. TemplateReactionRegulation  (label='Transcription/Translation')

**Notes**
- No name: Use some [Traverse](http://www.pathwaycommons.org/pc2/#traverse) to construct a default name, likely unique solution for each type.

**Comment by IgorRodchenkov** [comment]
Done in the app-ui repo.
