### ISSUE TITLE
Filter out search hits with 0 interactions

### ISSUE THREAD

**Issue by jvwong** [PathwayCommons/pathways-search#16]
The few examples that I've tried don't return any pathway elements when the search hit displays 0 interactions. Propose to filter out in Search list.

**Comment by mj3cheun** [comment]
Technically not difficult, I guess the only question I have is if we lose anything by filtering out hits with size 0, keeping in mind we plan to add more tabs in later (publications etc...). Also keep in mind that if we filter client side, the existing pagination system where the server returns a max of 100 items and therefore we display 100 items per page won't work as well. We will have to deal with having an unpredictable number of items per page instead.

**Comment by mj3cheun** [comment]
On further thought, best option is to have the filter be done server side. Next best option may be to have a client-side filter option in the filters panel that we previously had? What do you think?

**Comment by mj3cheun** [comment]
FIxed in commit 4690eaa6d06142055de5279a1b2a7ced0219c92e.

On further experimentation, I simply dropped all search results where size is 0. In vast majority of cases, the drop in number of items per page is unnoticeable to the user.
