### ISSUE TITLE
Use npm scripts; don't require global npm installs

### ISSUE THREAD

**Issue by maxkfranz** [PathwayCommons/pathways-search#17]
Use npm scripts so things like webpack don't need to be installed globally: https://docs.npmjs.com/misc/scripts

Some targets:

- `build` : run webpack on the project to do a prod build
- `watch` : use the webpack dev server with live reloading
- `start` : do a prod build using webpack and then serve using [`http-server`](https://www.npmjs.com/package/http-server)

**Comment by mj3cheun** [comment]
Fixed in e767f124b87b95b4fa6105fa389bed477c3df0f9. Switched to npm as general build tool.
