### ISSUE TITLE
Bad URI hangs viewer

### ISSUE THREAD

**Issue by jvwong** [PathwayCommons/pathways-search#21]
Base case: 
- NCI p53 pathway
- http://mj3cheun.github.io/pathways-search.html#/pathway?uri=http%3A%2F%2Fpathwaycommons.org%2Fpc2%2FPathway_1d99625aa7f8f4a3f3189e8b237522c3

Breaking case (altered): 
http://mj3cheun.github.io/pathways-search.html#/pathway?uri=http%3A%2F%2Fpathwaycommons.org%2Fpc2%2FPathway_1d99625aa7f8f4a3f3189e8b2237522c3

Behaviour should be to indicate some UI message and fail elegantly.

**Comment by mj3cheun** [comment]
Fixed in commit 99bd9c8bc1d22626431fae8356866c899a2588f5. Added error message for bad URI.
