### ISSUE TITLE
Feedback links 

### ISSUE THREAD

**Issue by jvwong** [PathwayCommons/pathways-search#22]
This exists in the form of a 'Help' link to our google group. Users may think Help is for help/bugs only. We should use the first production version as an information gathering stage to improve.   

Consider 'Feedback' or similar link and put in prominent place(s). I don't mind routing this to pathwaycommons@gmail.com but we could set up a temp address (e.g. pathwaycommons-feedback@gmail ??.

**Comment by mj3cheun** [comment]
Fixed in commit 9f951ed3e05a5a854d72420a5c275c4098c77b84. Used pathwaycommons@gmail.com as feedback link in footer.
