### ISSUE TITLE
Include Export for the Cytoscape JSON file

### ISSUE THREAD

**Issue by cannin** [PathwayCommons/pathways-search#25]
Add an export option for this file type. It will aid users in viewing/interacting with the network in Cytoscape Desktop.

**Comment by mj3cheun** [comment]
Fixed in commit ce3cff3b5d13fb827426a19a1ffecfbe0cf375cf. Added Cytoscape JSON download. Have updated the code on http://mj3cheun.github.io/pathways-search.html#/search. Is this the file format you are looking for?

**Comment by cannin** [comment]
Thanks. That was fast.
