### ISSUE TITLE
Search Bar tooltip text

### ISSUE THREAD

**Issue by jvwong** [PathwayCommons/pathways-search#28]
Suggest text:

-- begin

Enter a keyword, phrase, gene name or gene id. Separate multiple items by clicking "Enter" after each. Submit the query by clicking the "Search" button.

-- end

How will the multiple items feature work on mobile...?

**Comment by mj3cheun** [comment]
At least on iOS, there is an enter button on the mobile keyboard, so everything should still work as intended.
