### ISSUE TITLE
Search helper / fuzzy search

### ISSUE THREAD

**Issue by d2fong** [PathwayCommons/pathways-search#3]
@jvwong you said that you wanted something like this for the search as a module right?
http://www.pathwaycommons.org/pcviz/

 @mj3cheun 
When you go to pcviz and click on the search bar and start typing the name of a gene, a list of possible genes are displayed.  
Heres a pic of what I mean:

![screen shot 2017-01-16 at 4 56 09 pm](https://cloud.githubusercontent.com/assets/2328291/22000372/bdb82f8e-dc0c-11e6-928a-71c88d6fef16.png)

Typing 'bc' in the search bar shows a list of genes.  @jvwong do you think this would be a good next step?

**Comment by jvwong** [comment]
FYI - GeneMania also has this (http://genemania.org/). 

I would not implement this functionality because search terms do not necessarily map to gene (symbols) but rather pathway names which are rather arbitrary.

**Comment by mj3cheun** [comment]
Closing, probably won't implement in near future.
