### ISSUE TITLE
capture the full graph when saving as img

### ISSUE THREAD

**Issue by d2fong** [PathwayCommons/pathways-search#31]
http://js.cytoscape.org/#cy.png

set the 'full' option to true.

Gary asked for the full graph to be captured when saving the image. @mj3cheun @jvwong

**Comment by mj3cheun** [comment]
@jvwong Ok, should we consider having two seperate buttons for both full graph and window view, or a switch in the settings which toggles between the two? I can see use cases for both functions.

**Comment by mj3cheun** [comment]
Added new button under download modal to get full pathway regardless of window view.

**Comment by jvwong** [comment]
This references #38
