### ISSUE TITLE
Omit CTD by default

### ISSUE THREAD

**Issue by jvwong** [PathwayCommons/pathways-search#32]
It was suggested by @IgorRodchenkov that

1. Most of the pathways are from CTD
2. Most of the CTD pathways are just one or two participants 

Suggest to omit by default in the filter and allow users to add-back.

**Comment by mj3cheun** [comment]
Ok I agree with doing this. Is the fact that most of these "pathways" involve only a few participants sufficient justification though? I think you told me at one point that it could be awkward to explain why we intentionally dropped CTD in code.

**Comment by jvwong** [comment]
Well this would be taken care of by judiciously chosen default filtering I suppose. Then the small items could be displayed when user selected 'show more results' button.

**Comment by mj3cheun** [comment]
That is true, almost forgot about that. If we pick to prioritise reasonably sized pathways, CTD will be dropped anyway. https://github.com/PathwayCommons/pathways-search/issues/30
