### ISSUE TITLE
Error on input

### ISSUE THREAD

**Issue by jvwong** [PathwayCommons/pathways-search#34]
Breaking case - 'Mitotic G1-G1/S phases'

Error is 500 Internal Server error. 

Is this because of the slash?

**Comment by mj3cheun** [comment]
Escape all Lucene special characters except when using free-text search (unprocessed).

**Comment by mj3cheun** [comment]
Fixed in commit 3fefd533344ddd51b7af51593ec5e85bb3389348. Added Lucene escaping.
