### ISSUE TITLE
Downloads: GMT in HGNC

### ISSUE THREAD

**Issue by jvwong** [PathwayCommons/pathways-search#39]
Currently the .gmt download recovers a file with Uniprot IDs. 
A major use case would be to have genes declared in HGNC namespace instead of Uniprot.

**Comment by mj3cheun** [comment]
Look into using Uniprot REST services for this task (http://www.uniprot.org/help/programmatic_access)

**Comment by mj3cheun** [comment]
Update: Did research and found that Uniprots service is not good. However, HGNC provides a way to do the conversion, see example (http://rest.genenames.org/search/uniprot_ids:P31946+OR+P61366).

**Comment by jvwong** [comment]
Are you considering doing this on the client? I keep hearing about BridgeDB (http://www.bridgedb.org/webservices/)

**Comment by jvwong** [comment]
Close this and reconsider if there is some user demand.
