### ISSUE TITLE
Indecipherable graph for 'Phosphorylation of CD3 and TCR zeta chains' (Reactome) - beta PC

### ISSUE THREAD

**Issue by jvwong** [PathwayCommons/pathways-search#43]
> Note this is relevant to beta.pathwaycommons.org NOT production

Pathway: 'Phosphorylation of CD3 and TCR zeta chains'
Source: Reactome
URI: http://identifiers.org/reactome/R-HSA-202427
SBGN: http://beta.pathwaycommons.org/pc2/get?uri=http://identifiers.org/reactome/R-HSA-202427&format=SBGN

![reactome_phosphocd3tcrzetachains_searchapp](https://cloud.githubusercontent.com/assets/4706307/24673222/836a2a82-1945-11e7-8646-2e3ca2632acf.png)

**Comment by mj3cheun** [comment]
Server side layouts is disabled for pathways beyond a certain size. In order to view larger pathways such as this, it is necessary to implement client-side layouts.

**Comment by jvwong** [comment]
Makes sense - I just noticed the production version renders fine. 
Should we be putting this as a note somewhere? I can see this coming up - this pathway was only 74 participants.

**Comment by mj3cheun** [comment]
I talked to Igor and he said something like if the pathway has over I think 1000 nodes it will just not render. I was thinking of leaving this issue off for now (most of my pathways render fine) and try to implement client side layouts for 2.1.

**Comment by jvwong** [comment]
OK let's punt this for now. The current outlook - we can ask @d2fong - is to *always* implement a client-side layout/rules.
