### ISSUE TITLE
Advanced: Clearing data sources 

### ISSUE THREAD

**Issue by jvwong** [PathwayCommons/pathways-search#44]
Within the Advanced modal, clicking the 'x' within the bounding box of the data source filter option deletes all the content from the entire modal.

This result is also occurs when all the data sources are removed individually. 

The expected behaviour is to clear the filtering data sources only then allow re-adding.

**Comment by mj3cheun** [comment]
Fixed in commit 088331dc466356f58af477b39afb66e5e535a018. Fixed datasource bug.
