### ISSUE TITLE
Disagreement when filtering by data source

### ISSUE THREAD

**Issue by jvwong** [PathwayCommons/pathways-search#45]
Breaking case: [Search for 'apoptosis'](http://mj3cheun.github.io/pathways-search.html#/search?gt=3&lt=200&q=apoptosis&type=Pathway) shows WikiPathways among results.

[Filtering for 'Wikipathways'](http://mj3cheun.github.io/pathways-search.html#/search?datasource=wp&gt=3&lt=200&q=apoptosis&type=Pathway) returns no results.

**Comment by mj3cheun** [comment]
Ticket filed with cpath2. https://github.com/PathwayCommons/cpath2/issues/265

**Comment by mj3cheun** [comment]
Fixed in commit 90833c7750e17ec5c406bddf5cc3e64ab6540e39. Switched from using id to name.
