### ISSUE TITLE
Advanced Tooltip floating in space

### ISSUE THREAD

**Issue by jvwong** [PathwayCommons/pathways-search#46]
The 'Search Options' tooltip appears in the home screen. Also it is pointing at the search box. 

![screenshot_advanced_issue](https://cloud.githubusercontent.com/assets/4706307/24707814/fe60a6d8-19e2-11e7-9619-50e7800eb762.png)

1. Should not be present if advanced option is not present. 
2.  Should refer to 'advanced' rather than 'search option'

**Comment by mj3cheun** [comment]
Fixed in commit 155bbb106a528ab9915ba08980bcb65c20ca2718. Fixed all bugs mentioned.
