### ISSUE TITLE
Handling server offline 

### ISSUE THREAD

**Issue by jvwong** [PathwayCommons/pathways-search#47]
The application presents a 'offline' screen:

![screenshot_offline_issue](https://cloud.githubusercontent.com/assets/4706307/24710559/7cb866da-19eb-11e7-94d1-28e3277afc93.png)

This prevents interaction with content (FAQ, splash)

Suggestion to replace with a less disruptive/global message or [alert](https://react-bootstrap.github.io/components.html#alerts).

**Comment by mj3cheun** [comment]
Fixed in commit 5680340d5c14643b77528381f914d37816557caa. Uses less disruptive alert to inform user of outage.
