### ISSUE TITLE
Displaying pathway-associated comments

### ISSUE THREAD

**Issue by jvwong** [PathwayCommons/pathways-search#48]
Question: How feasible is it to display the comments associated with pathways?

For several of the pathways that I am familiar with - e.g. Signaling by BMP (Reactome) [uri=http%3A%2F%2Fidentifiers.org%2Freactome%2FR-HSA-201451] - there is tremendously valuable free-text associated with the pathway.

> <bp:Pathway rdf:about="http://identifiers.org/reactome/R-HSA-201451">
  ...
  <bp:comment rdf:datatype = "http://www.w3.org/2001/XMLSchema#string">Authored: Huminiecki, L, Moustakas, A, 2007-11-07 10:22:00</bp:comment>
  <bp:comment rdf:datatype = "http://www.w3.org/2001/XMLSchema#string">Bone morphogenetic proteins (BMPs) have many biological activities in various tissues, including bone, cartilage, blood vessels, heart, kidney, neurons, liver and lung. They are members of the Transforming growth factor-Beta (TGFB) family. They bind to type II and type I serine-threonine kinase receptors, which transduce signals through SMAD and non-SMAD signalling pathways. BMP signalling is linked to a wide variety of clinical disorders, including vascular diseases, skeletal diseases and cancer. BMPs typically activate BMP type I receptors and signal via SMAD1, 5 and 8. They can be classified into several subgroups, including the BMP2/4 group, the BMP5-8 osteogenic protein-1 (OP1) group, the growth and differentiation factor (GDF) 5-7 group and the BMP9/10 group. Most of the proteins of the BMP2/4, OP1 and BMP9/10 groups induce formation of bone and cartilage tissues in vivo, while the GDF5-7 group induce cartilage and tendon-like, but not bone-like, tissues (Miyazono et al. 2010). Members of the TGFB family bind to two types of serine-threonine kinase receptors, type I and type II (Massagué 2012). BMPs can bind type I receptors in the absence of type II receptors, but both types are required for signal transduction. The presence of both types dramatically increases binding affinity (Rozenweig et al. 1995). The type II receptor kinase transphosphorylates the type I receptor, which transmits specific intracellular signals. Type I and type II receptors share similar structural properties, comprised of a relatively short extracellular domain, a single membrane-spanning domain and an intracellular domain containing a serine-threonine kinase domain. Seven receptors, collectively referred to as the Activin receptor-like kinases (ALK), have been identified as type I receptors for the TGFB family in mammals. ALKs are classified into three groups based on their structure and function, the BMPRI group (Bone morphogenetic protein receptor type-1A, ALK3, BMPR1A and Bone morphogenetic protein receptor type-1B, ALK6, BMPR1B), the ALK1 group (Serine/threonine-protein kinase receptor R3, ALK1, ACVRL1 and Activin receptor type-1, ALK2, ACVR1) and the TBetaR1 group (Activin receptor type-1B, ALK4, ACVR1B and TGF-beta receptor type-1, ALK5, TGFBR1 and Activin receptor type-1C, ALK7, ACVR1C) (Kawabata et al. 1998). ALK1 group and BMPRI group activate SMAD1/5/8 and transduce similar intracellular signals. The TBetaR1 group activate SMAD2/3. BMPR1A and ACVR1 are widely expressed. BMPR1B shows a more restricted expression profile. ACVRL1 is limited to endothelial cells and a few other cell types. The binding specificities of BMPs to type I receptors is affected by the type II receptors that are present (Yu et al. 2005). Typically, BMP2 and BMP4 bind to BMPR1A and BMPR1B (ten Dijke et al. 1994). BMP6 and BMP7 bind strongly to ACVR1 and weakly to BMPR1B. Growth/differentiation factor 5 (BMP14, GDF5) preferentially binds to BMPR1B, but not to other type I receptors (Nishitoh et al. 1995). BMP9 and BMP10 bind to ACVRL1 and ACVRL (Scharpfenecker et al. 2007). BMP type I receptors are shared by other members of the TGFB family. Three receptors, Bone morphogenetic protein receptor type-2 (BMPR2), Activin receptor type-2A (ACVR2A) and Activin receptor type-2B (ACVR2B) are the type II receptors for mammalian BMPs. They are widely expressed in various tissues. BMPR2 is specific for BMPs, whereas ACVR2A and ACVR2B are shared with activins and myostatin. BMP binding and signalling can be affected by coreceptors. Glycosylphosphatidylinositol (GPI)-anchored proteins of the repulsive guidance molecule (RGM) family, including RGMA, RGMB (DRAGON) and Hemojuvelin (HFE2, RGMC) are coreceptors for BMP2 and BMP4, enhancing signaling (Samad et al. 2005, Babitt et al. 2005, 2006). They interact with BMP type I and/or type II receptors and bind BMP2 and BMP4, but not BMP7 or TGFB1. BMP2/4 signalling normally involves BMPR2, not ACVR2A or ACVR2B. Cells transfected with RGMA use both BMPR2 and ACVR2A for BMP-2/4 signalling, suggesting that RGMA facilitates the use of ACVR2A by BMP2/4 (Xia et al. 2007). Endoglin (ENG) is a transmembrane protein expressed in proliferating endothelial cells. It binds various ligands including TGFB1/3, Activin-A and BMP2/7 (Barbara et al. 1999). It inhibits TGFB-induced responses and enhances BMP7-induced responses (Scherner et al. 2007). Mutations in ENG result in hereditary haemorrhagic telangiectasia (HHT1), also known as OslerWeberRendu disease, while mutations in ACVRL1 lead to HHT2, suggesting that they act in a common signalling pathway (McAllister et al. 1994, Johnson et al. 1996). BMP2 is a dimeric protein, having two receptor-binding motifs. One is a high-affinity binding site for BMPR1A, the other is a low-affinity binding site for BMPR2 (Kirsch et al. 2000). In the absence of ligand stimulation, small fractions of type II and type I receptors are present as preexisting homodimers and heterodimers on the cell surface. Ligand-binding increases oligomerization. The intracellular domains of type I receptors have a characteristic GS domain (glycine and serine-rich domain) located N-terminal to the serine-threonine kinase domains. Type II receptor kinases are constitutively active in the absence of ligand. Upon ligand binding, the type II receptor kinase phosphorylates the GS domain of the type I receptor, a critical event in signal transduction by the serine/threonine kinase receptors (Miyazono et al. 2010). Activation of the TGFBR1 receptor has been studied in detail. The inactive conformation is maintained by interaction between the GS domain, the N-terminal lobe and the activation loop of the kinase (Huse et al. 1999). When the GS domain is phosphorylated by the type II receptor kinase, the TGFBR1 kinase is converted to an active conformation. Mutations of Thr-204 in TGFBR1 and the corresponding Gln in BMP type I receptors lead to their constitutive activation. The L45 loop, in the kinase domain of type I receptors, specifically interacts with receptor-regulated Smads (R-Smads). Neurotrophic tyrosine kinase receptor type 3 (NT-3 growth factor receptor, TrkC, NTRK3) directly binds BMPR2, interfereing with its interaction with BMPR1A, which inhibits downstream signalling (Jin et al. 2007). Tyrosine-protein kinase transmembrane receptor ROR2 and BMPR1B form a heteromeric complex in a ligand independent fashion that modulatesGDF5-BMPR1B signalling by inhibition of Smad1/5 signalling (Sammar et al. 2004). Type I receptor kinases activated by the type II receptor kinases, phosphorylate R-Smads. R-Smads then form a complex with common-partner Smad (co-Smad) and translocate to the nucleus. The oligomeric Smad complexes regulate the transcription of target genes through interaction with various transcription factors and transcriptional coactivators or corepressors. Inhibitory Smads (I-Smads) negatively regulate the action of R-Smads and/or co-Smads. Eight different Smads have been identified in mammals. Smad1, Smad5 and Smad8 are R-Smads in BMP signalling pathways (BMP-specific R-Smads). Smad2 and Smad3 are R-Smads in TGFB/activin&lt;br&gt;signalling pathways. BMP receptors can phosphorylate Smad2 in certain types of cells (Murakami et al. 2009). Smad1, Smad5 and Smad8 are structurally highly similar to each other. The functional differences between them are largely unknown. Smad4 is the only co-Smad in mammals, shared by both BMP and TGFB/activin signalling pathways. Smad6 and Smad7 are I-Smads.
  </bp:comment>
  <bp:comment rdf:datatype = "http://www.w3.org/2001/XMLSchema#string">Reviewed: Heldin, CH, 2007-11-12</bp:comment>
  <bp:dataSource rdf:resource="#reactome" />
</bp:Pathway>

**Comment by mj3cheun** [comment]
Ok, neat idea and not too hard to do, but I think the biggest problem we have is where to put the comments, since the tabs are gone now. First of all, we need to get the comments in the first place, which means a simple traverse query (http://www.pathwaycommons.org/pc2/traverse?uri=http%3A%2F%2Fidentifiers.org%2Freactome%2FR-HSA-201451&path=Entity/comment). Then we need to spit it out on the page somewhere. Maybe a comments modal box?

**Comment by jvwong** [comment]
This would be super helpful for users. 

UI display is to have 'info' link to the immediate right of the 'source'. I realize it's getting crowded up there and might impinge upon different screen sizes. Inside, each comment tag would be laid out as a paragraph. If there is a ton of text, it is scrollable within a modal. Is it bad form to have a sidebar? I think this is de rigeur for info. 

Are you already doing this traverse to grab the source? In that case it's just grabbing another, potentially more useful item.

![reactome](https://cloud.githubusercontent.com/assets/4706307/24770664/bfe95502-1ad8-11e7-9989-304dd3450994.png)

**Comment by mj3cheun** [comment]
Yes I am doing a traverse to grab the source. I don't think sidebar is a particularly good idea, since it will reduce the area usable by the renderer, and at the same be too skinny for good reading. Modals should work well enough and can scroll if there is a lot of text. As for the location of the button, you want it beside "REACTOME" in the example, or beside "Downloads"? Either should work.

**Comment by jvwong** [comment]
It makes sense to place it to the immediate right of the data source.

'pathway displayname' | 'source' | 'Info'

**Comment by mj3cheun** [comment]
Ok sure.

**Comment by mj3cheun** [comment]
Added prototype in commit 083f5402da1544b1a9a6af0fc6791fc3cdd6cef9.
