### ISSUE TITLE
FAQ: How does [enhanced] search work?

### ISSUE THREAD

**Issue by jvwong** [PathwayCommons/pathways-search#61]
Suggestion to change this to 'How does the search work?'. 

- Update this description to be understandable to a less technical audience.
- Illustrate using a  couple of concrete examples
  - pathway name 
  - list of gene symbols

e.g. 
name: PD-1 SIGNALING
HUGO: CSK	HLA-DRA	PDCD1	PTPN11	CD274	LCK	HLA-DRB4	HLA-DRB5	HLA-DPA1	CD4	CD3D	CD3G	CD3E	HLA-DRB1	HLA-DQA2	HLA-DRB3	HLA-DQA1	PDCD1LG2	HLA-DQB1	PTPN6	HLA-DQB2

**Comment by IgorRodchenkov** [comment]
Refs PathwayCommons/cpath2#269 - see some examples here, though that only indirectly relates to pathways-search app.

**Comment by jvwong** [comment]
FYI

Commit (c5e212c8f88a0b006ddf91b2f89db98773fab7e2) app's [logic for adding lucene syntax](https://github.com/PathwayCommons/pathways-search/blob/c5e212c8f88a0b006ddf91b2f89db98773fab7e2/js/search/helpers/queryProcessing.js#L62-L65)
