### ISSUE TITLE
No pathway displayed

### ISSUE THREAD

**Issue by jvwong** [PathwayCommons/pathways-search#62]
No pathway image is displayed for search result.

Breaking case:

C-MYC pathway from NCI-PID

http://localhost:8080/#/pathway?uri=http%3A%2F%2Fpathwaycommons.org%2Fpc2%2FPathway_78c1a86e97b8823afd57833065c64f65

**Comment by mj3cheun** [comment]
This is the strangest bug I have ever seen. There is a pathway image there, it is just laid out so that it is zoomed so far out you cannot see it. See picture.
![graph32592190](https://cloud.githubusercontent.com/assets/14062458/25249303/710b9a82-25df-11e7-9ae3-d4eb7d11630f.png)

**Comment by jvwong** [comment]
Agreed that is what I see. I'll close this as it's a layout issue.

**Comment by IgorRodchenkov** [comment]
http://beta.pathwaycommons.org/pathways/#/pathway?uri=http%3A%2F%2Fpathwaycommons.org%2Fpc2%2FPathway_78c1a86e97b8823afd57833065c64f65

Looks like a layout issue (that comes from PC uses Paxtools' sbgn-converter uses chilay-sbgn...)
PathwayCommons/chilay-sbgn#1
