### ISSUE TITLE
Make user aware of direct entry by URI

### ISSUE THREAD

**Issue by jvwong** [PathwayCommons/pathways-search#64]
Suggestion to make find by URI explicit

- placeholder text like GOogle?
- FAQ entry or within existing FAQ

**Comment by jvwong** [comment]
See text box:

![search](https://cloud.githubusercontent.com/assets/4706307/25343694/bf53e7a2-28dd-11e7-8c2b-5861f9777788.png)

**Comment by mj3cheun** [comment]
Tweaked in commit c21b93adf3f9b90f3da61cc668db75692f384c88.Changed placeholder text.
