### ISSUE TITLE
Top header "Pathway Commons" link

### ISSUE THREAD

**Issue by jvwong** [PathwayCommons/pathways-search#65]
Currently when you click on this link, it brings you back to the app home page, not the PC homepage.  

Suggestion: 
  - change header to the app name (e.g. Pathway Commons pathway search and view, or similar) 
  - have a prominent link back to the PC homepage.

**Comment by mj3cheun** [comment]
We could revert back to the way it was before, so "Pathways Search" or similar in the header bar, and "Pathway Commons" in the splash.

**Comment by jvwong** [comment]
Adding this and additional changes to front page:
  - Logo update: [Pathway Search](http://www.pathwaycommons.org/pathways/#/search)
  - Splash updates
    - Title: Search [Pathway Commons](http://www.pathwaycommons.org/)  
    - Footer:  [Help](https://groups.google.com/forum/#!forum/pathway-commons-help/)

![search](https://cloud.githubusercontent.com/assets/4706307/25343623/97ec1c66-28dd-11e7-9326-8e63240ccb46.png)

**Comment by mj3cheun** [comment]
Fixed in commit c21b93adf3f9b90f3da61cc668db75692f384c88. Tweaked splash.

**Comment by jvwong** [comment]
Can we update the title too? Right now it says ```Pathway Commons``` 
But that should be something like ```Search```

**Comment by mj3cheun** [comment]
Sure, on it...

**Comment by mj3cheun** [comment]
Done
