### ISSUE TITLE
Many repeats of nodes in pathway diagrams

### ISSUE THREAD

**Issue by cannin** [PathwayCommons/pathways-search#67]
I'm not sure why the following issue happens, but GAPDH appears 10 times in the glycolysis pathway; others appear multiple times, too. It makes for unnecessarily complex diagrams.

![screen shot 2017-04-24 at 12 40 54 pm](https://cloud.githubusercontent.com/assets/790284/25393256/042b2aae-29a9-11e7-9536-44c5b6919f3f.png)

**Comment by jvwong** [comment]
moved to PathwayCommons/viewer-component/issues/4
