### ISSUE TITLE
Increase default max pathway size

### ISSUE THREAD

**Issue by mj3cheun** [PathwayCommons/pathways-search#68]
The default max participants number is 200, which removes a number of important pathways such as "Interferon Gamma Signaling". Propose changing it to 300 for this reason.

**Comment by IgorRodchenkov** [comment]
@mj3cheun @d2fong @jvwong 
Could you fix this and also merge the other branch into the master?
Or we could do this if it's ok/ready...

**Comment by mj3cheun** [comment]
@IgorRodchenkov Master is latest. Fixed in commit c5e212c8f88a0b006ddf91b2f89db98773fab7e2.
