### ISSUE TITLE
Edit out pathways by default

### ISSUE THREAD

**Issue by jvwong** [PathwayCommons/pathways-search#84]
Before release, let's review the performance of the layouts and hide/remove by default those that fail to meet some basic sanity test.

- pathway participant numbers
- data providers
- other constraints?

**Comment by d2fong** [comment]
Not really editing out pathways, but we could try to determine what type of pathway it is (metabolic / signalling) which could give us some info about which layout to use e.g check if it has compartments, etc.

**Comment by jvwong** [comment]
Suggest hiding

- All Wikipathways

**Comment by d2fong** [comment]
I think some of the wikipathways [here (filter for wikipathways)](http://192.168.81.233:8080/#/search?datasource=WikiPathways&gt=3&lt=250&q=pathway&type=Pathway) look okay to me, but that is purely from a visual perspective.  I am not sure how useful these are apart from that.

**Comment by d2fong** [comment]
I looked at the pathways returned by searching 'pathway'.  The most common culprits are smpdb and pid pathways. 

pathwaycommons.org%2Fpc2%2FPathway_aa30482c96d8af05cbfbc136a2a95266  IL12 signaling mediated by STAT4 | pid
http%3A%2F%2Fpathwaycommons.org%2Fpc2%2FPathway_f77c02fc3255fe850fd2e8045d2e7bc6  Trk receptor signaling mediated by the MAPK pathway | pid

pathwaycommons.org%2Fpc2%2FPathway_c788395e069cedcba7af3572cc52b62e Signaling events mediated by PTP1B | pid
pathwaycommons.org%2Fpc2%2FPathway_536ed31dd15201fc67b595d07cf90c76 Signaling events mediated by the Hedgehog family | pid

http%3A%2F%2Fidentifiers.org%2Fsmpdb%2FSMP00031 Pentose Phosphate Pathway | SMPDB

http%3A%2F%2Fidentifiers.org%2Fsmpdb%2FSMP00132 Triamterene Action Pathway | SMPDB
http%3A%2F%2Fidentifiers.org%2Fsmpdb%2FSMP00367 Carvedilol Action Pathway | SMPDB
http%3A%2F%2Fpathwaycommons.org%2Fpc2%2FPathway_6569b23e570f2d5c6d8ee9ddba51595a Arf6 signaling events | pid
http%3A%2F%2Fpathwaycommons.org%2Fpc2%2FPathway_bdb238bd98437baa87f820e4e5effaf3 p75(NTR)-mediated signaling | pid
http%3A%2F%2Fidentifiers.org%2Fwikipathways%2FWP1984 Integrated Breast Cancer Pathway | WikiPathways


maybe

http%3A%2F%2Fidentifiers.org%2Fsmpdb%2FSMP00110 Indapamide Action Pathway | SMPDB
http%3A%2F%2Fidentifiers.org%2Fsmpdb%2FSMP00396 Dibucaine Action Pathway | SMPDB
http%3A%2F%2Fidentifiers.org%2Fsmpdb%2FSMP00395 Cocaine Action Pathway | SMPDB
http%3A%2F%2Fpathwaycommons.org%2Fpc2%2FPathway_2b429898c1df6a17e6989aae6ba99c34 Integrin-linked kinase signaling | pid
http%3A%2F%2Fidentifiers.org%2Fsmpdb%2FSMP00306 Pindolol Action Pathway | SMPDB
http%3A%2F%2Fidentifiers.org%2Fsmpdb%2FSMP00304 Oxprenolol Action Pathway | SMPDB
http%3A%2F%2Fpathwaycommons.org%2Fpc2%2FPathway_875e0401d17fc1e8766f60dd9e0d5cff ATF-2 transcription factor network | pid



abnormal

http%3A%2F%2Fidentifiers.org%2Fsmpdb%2FSMP00155 Rescinnamine Action Pathway | SMPDB
http%3A%2F%2Fpathwaycommons.org%2Fpc2%2FPathway_81a741c3dac77f5c3a2b2af0e0fcc15b ErbB receptor signaling network | pid

**Comment by jvwong** [comment]
I agree about the SMPDB pathways but the PID ones look passable to me. I'd say about 30% of wikipathways have some bizarre (unknown process; no name nodes) aspects.

**Comment by IgorRodchenkov** [comment]
Sometimes it's better keep info than hide. All data sources have some
issues. Let's keep everything (unless something makes the app or server
hang or fail) and briefly explain in a doc that original pathway data
quality and level or detail vary, which causes such visualisations.

There are no "unknown process" glyphs.. did you mean "omitted process"?
These come from either "Interaction" (base) BioPAX class or
GeneticInteraction (rare).

PS:
If we'd keep as much as possible pathways, we e.g., could show and prove to
the data providers (WP, SMPDB) that there is much room for improvement in
their BioPAX, and looks nobody can do this for them, which might ignite
activity on their side...

**Comment by jvwong** [comment]
I think the work on the  layouts ( @d2fong ) and debugging ( @IgorRodchenkov ) has really reduced a lot of the so-called problems with some of the pathways from various data sources. Also I think that what @d2fong has mentioned is correct: That smaller pathways generally look really good now.

One simple option is to default the filter to something like 3 < participants < 100. People can always change the filter defaults.

The ultimate solution is to arrange these things by hand ( #71  ).  Maybe a student could take this on...

**Comment by d2fong** [comment]
I tried using the cytoscape dagre layout and it looks good on some graphs too. Sometimes it is better than klay but other times it looks worse. 

I think users will be able to get a good result most of the time by using one of klay, dagre, and cola.

**Comment by d2fong** [comment]
Klay looks best on larger graphs.  Dagre and cola look good on smaller ones

**Comment by jvwong** [comment]
yeah I like this dagre thing.
