### ISSUE TITLE
Show SBGN logo somewhere

### ISSUE THREAD

**Issue by IgorRodchenkov** [PathwayCommons/pathways-search#86]
I think it'd help and be honest to display an "SBGN PD" logo (link to sbgn.org) somewhere on the network view pages.

**Comment by jvwong** [comment]
This is a good point that Dylan also raised - users (aka biologists) generally have a hard time understanding SBGN-PD. For example, 'what are process nodes'? Most biologists are used to activity flow.

I wanted to create an actual 'Help' page that contains the FAQ that would describe SBGN etc  - #78

**Comment by jvwong** [comment]
I've added a Help link in 96f7c8fb1e8e66f04478242e3880430dd7143a8b. This is related to #78 so closing.
