### ISSUE TITLE
FAQ: How does search work - does not mention search by IDs

### ISSUE THREAD

**Issue by IgorRodchenkov** [PathwayCommons/pathways-search#88]
In `http://beta.pathwaycommons.org/pathways/#/faq`, "How does search work" should probably begin with (item 0) about what if a user query/phrase contains a valid identifier (- then, a.f.a.i.k, only ID(s) is used to query in 'xrefid' index field, and all other words in the input are ignored)

**Comment by jvwong** [comment]
I think we briefly talked about this: There was [no prefixing with ``` xrefid``` when I picked up the app](https://github.com/PathwayCommons/pathways-search/blob/c5e212c8f88a0b006ddf91b2f89db98773fab7e2/js/search/helpers/queryProcessing.js#L62).

**Comment by IgorRodchenkov** [comment]
It's not about prefixing at all. It's about auto-detecting IDs in a query phrase first and then internally forcing search in xrefid. Remember? It works that way right now, no? It should.

**Comment by jvwong** [comment]
What's the operational difference between prefixing with xrefid and internally forcing search in xrefid?

**Comment by IgorRodchenkov** [comment]
Well, you're right that there was no use of 'xrefid:' prefix since we've designed with Manfred (he found a workaround).  And, more important, everything seems to work very well, and it's hard to prove otherwise (partially due to a side effect of PathwayCommons/cpath2-client#3 bug)...

**FYI** (optional but interesting reading).

Initially, the whole idea of detecting IDs from user's input was to use 'xrefid:' search internally or at least to query those words without using any prefix or order. Now I see that much of code has changed since after Manfred's done, and after we first added wildcards (*) there.

But, my point is that all words (user query tokens) must participate in a search query and have a chance to match. Currently we allow only auto-detected IDs ([8 types](https://github.com/PathwayCommons/cpath2-client/blob/master/src/private/constants.js), and where the 'hgnc' pattern captures almost everything) to match without any field name prefix, while all other words are prefixed with 'name:' (wrapped as 'name:" + "*" + word + "*"' always), and entire input phrase is prefixed with 'name:' as well. I think, we should simply add one more sub-query like `"(" + escapeSpaces( words ) + ") OR ("` in addition to what's [already there](https://github.com/PathwayCommons/pathways-search/blob/8bcfe86f290a5e6bf2e0be019c26ceb77dcc33ea/js/search/helpers/queryProcessing.js#L77) (note: here I am suggesting 'words' - original tokens - array, not 'result', to be used, and - no 'name:' prefix).
Finally (having suggested sub-query), **we do not have to detect bio IDs with regexp** (it does not improve the search).  

For example, one can find Reactome "Meiotic recombination" using not only [Q06609](http://www.uniprot.org/uniprot/Q06609) or RAD51 or NP_002866, but also - gene ID: 5888 - via PC API:
http://beta.pathwaycommons.org/pc2/search?type=pathway&datasource=reactome&q=5888
http://beta.pathwaycommons.org/pc2/search?type=pathway&datasource=reactome&q=xrefid:5888

If not [this issue](/PathwayCommons/cpath2-client/issues/3), pathways-search would not probably find that pathway using the gene ID 5888:

http://beta.pathwaycommons.org/pathways/#/search?datasource=Reactome&gt=3&lt=250&q=5888&type=Pathway (magically works thanks to bugs...)

**Comment by jvwong** [comment]
For aeaa631c6df189f432d5113c08a7228979a57e8c: 
  - Added refseq to checkList of identifiers it would compare tokens against
  - Refactored if statements to be more explicit about each stage (```failureCount```) 

Theres a looootttttt of room to improve ( #75 #82 ) but it kinda works OK for now. 

If I search ```Jeffrey Wong```: 
```
Inhibition of Signaling by Overexpressed EGFR 
Reactome
15 Participants
```
