### ISSUE TITLE
Highlight neighbouring processes + entities

### ISSUE THREAD

**Issue by jvwong** [PathwayCommons/pathways-search#95]
> I would change nearest neighbors to highlight processes that current node is involved in. In other words, it would behave the same if the node is a process but if it’s an EPN then not only the neighboring processes but also the substrates/products/modulators of those processes would be highlighted. For instance when mouse is over actin, 2 processes that actin is involved in are highlighted:

**Comment by IgorRodchenkov** [comment]
Done in the app-ui repo.
