### ISSUE TITLE
Managing state variables

### ISSUE THREAD

**Issue by jvwong** [PathwayCommons/pathways-search#98]
Many pathway instances have state variables that are ambiguous, distracting and often not very helpful.

e.g. 1  [Signaling by BMP](http://beta.pathwaycommons.org/pathways/#/view?uri=http%3A%2F%2Fidentifiers.org%2Freactome%2FR-HSA-201451) displays state variable ```x[283-396]``` for the BMP dimer that originates from a 'FragmentFeature' in the corresponding BioPAX. Guessing from Reactome/Unirprot, this may indicate the amino acid region of the mature form originating from a pro-protein (http://www.uniprot.org/uniprot/P12643#ptm_processing). 

At best this is distracting and unnecessarily clutters an already busy network. Also the meaning of this information should be more clear to a user / biologist user -  or hidden/filtered out. 

Also [Newt](http://www.cs.bilkent.edu.tr/~ivis/ChiSE_daily/) sometimes does not display this information

Example when it doesn't display meaningless state variables:
http%3A%2F%2Fidentifiers.org%2Freactome%2FR-HSA-201451

Example when it does:
http%3A%2F%2Fidentifiers.org%2Freactome%2FR-HSA-6803211

![screen shot 2017-07-14 at 12 39 06 pm](https://user-images.githubusercontent.com/2328291/28221497-8380094c-6891-11e7-8758-cd5286ba3585.png)

I suspect the difference maybe just in how many of these state variables they choose to render.

**Comment by d2fong** [comment]
Newt does display stuff like ```x[1-393]``` sometimes. 
Check this one:
http%3A%2F%2Fidentifiers.org%2Freactome%2FR-HSA-6803211

Why they do it sometimes but not always, I don't know.

**Comment by jvwong** [comment]
For clarity and complexity management, some of these features (BioPAX parlance)  must be displayed as units of information (e.g. phosphorylation) as they communicate important differences in state. 

Aside relevant to SBGN-converter: Some state variables have pretty cryptic text. For example, [BMP Receptor Signaling from PID](http://beta.pathwaycommons.org/pathways/#/view?uri=http%3A%2F%2Fpathwaycommons.org%2Fpc2%2FPathway_eb9be568a2c75cb8fad9e5c47f250f20)(http%3A%2F%2Fpathwaycommons.org%2Fpc2%2FPathway_eb9be568a2c75cb8fad9e5c47f250f20) provides a ModificationFeature 'residue modification, inactive' in BioPAX but the corresponding SBGN-ML state value is 'Ina'? 

Remaining could be considered as additional metadata placed in a context menu along with the other stuff (e.g. 'FragmentFeature').

**Comment by jvwong** [comment]
also see https://github.com/PathwayCommons/cytoscape-sbgn-stylesheet/issues/72

**Comment by IgorRodchenkov** [comment]
Done in the app-ui repo.
